version: "3.8"
services:
  bot:
    restart: always
    build: 
      context: .
      args:
        APP_NAME: partypoll
    env_file:
      - .env
    # command: /bin/sh -c "while :; do sleep 10; done"
